ms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views

app_name='music'

urlpatterns=[
    path('',views.IndexView.as_view(), name="index"),
    path('<pk>/',views.DetailView.as_view(), name="detail"),
    path('album/add/',views.AlbumCreate.as_view(), name="album-add"),
    path('album/<pk>/',views.AlbumUpdate.as_view(), name="album-update"),
    path('album/<pk>/delete/',views.AlbumDelete.as_view(), name="album-delete"),
]

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist=models.CharField(max_length=200)
    title=models.CharField(max_length=200)
    genre=models.CharField(max_length=200)
    logo=models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + "->" + self.artist


class Songs(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    sname=models.CharField(max_length=200)
    type=models.CharField(max_length=10)
    isfav=models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.sname

music/templates/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from .models import Album,Songs
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    template_name = "music/index.html"

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = "music/detail.html"


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','title','genre','logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','title','genre','logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Album</title>
    <div class="ao">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'music/form-template.html' %}
            <hr>
            <button type="submit">Submit</button>
        </form>

    </div>
</head>
<body>

</body>
{% endblock %}
</html>

music/templates/music/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "music/styles.css" %}" />
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SongApp</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css2?family=Tillana:wght@500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">SongApp</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span>Register</a></li>
      <li><a href="{% url 'music:album-add' %}"><span class="glyphicon glyphicon-plus"></span>Login</a></li>
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>songs</title>
</head>
<div class="bod">
<body style="text-align: center;text-decoration: aqua;">
{% if album %}
    <div class="ao">
    <div class="ab">
    <h1>{{ album.title }}</h1>
    <img src={{ album.logo.url }} height=200px>
    <h2>{{ album.artist }}</h2></div>
    <br><br>
    <hr>

    {% if error_message %}
        <h1>{{ error_message}}</h1>
    {% endif %}
    {% for song in album.songs_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
            <label for="song{{ forloop.counter }}">
            {{ song.sname }}
            </label>
             <button><span class="glyphicon glyphicon-trash"></span></button>
                <button><span class="glyphicon glyphicon-star"></span></button></li>
        <hr>

    {% endfor %}
    </div>
    {% else %}
    <h1>bhapp</h1>
{% endif %}

</body>
</div>
{% endblock %}
</html>

music/templates/music/form-template.html
{% for field in form %}
    <div>
    <span>{{ field.errors }}</span>
    <label>{{ field.label_tag }}</label>
    <div>{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
    <div class="bod">
    <ul>
        <div>
        {% for album in object_list %}
            <li class="bo"><a  href="{% url 'music:detail' album.id %}"><img src={{ album.logo.url }} height=250px width="250px"><br><h2>{{ album.title }}</h2></a>
                <br><button>View Details</button>   <form action="{% url 'music:album-delete' album.id %}" method="post">
                    {% csrf_token %}
                    <button><span class="glyphicon glyphicon-trash"></span></button>
                <button><span class="glyphicon glyphicon-star"></span></button>
        </form>
            </li>

        {% endfor %}
        </div>
    </ul></div>
{% endblock %}